KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="kafka-dev-secret"
  user_admin="kafka-dev-secret"
  user_ecommerce="ecommerce-secret";
};

Client {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="ecommerce"
  password="ecommerce-secret";
};
